### ISSUE TITLE
likelihood at epoch 4 : nan

### ISSUE THREAD

**Issue by duanyanan** [diningphil/CGMM#3]
I clone this repo and create dataset NCI1 use `python PrepareDatasets.py DATA --dataset-name NCI1`, then I set model to CGMM in config_CGMM.yml, and I run experiment in this cmd `python Launch_Experiments.py --config-file config_CGMM.yml --inner-folds 5 --outer-folds 10 --dataset NCI1`, but it shows as follow
```Initializing layer 1 of CGMM...
Initializing layer 1 of CGMM...
Initializing mu with subset of samples...
Done.
Initializing mu with subset of samples...
Done.
likelihood at epoch 1 : -18385428.75233797
likelihood at epoch 1 : -18450323.068600252
likelihood at epoch 2 : 29223505.57830939
likelihood at epoch 2 : 20955841.784109604
likelihood at epoch 3 : 45010385.37719304
likelihood at epoch 3 : 33882714.402603015
likelihood at epoch 4 : nan
likelihood at epoch 4 : nan
likelihood at epoch 5 : nan
likelihood at epoch 5 : nan
likelihood at epoch 6 : nan
likelihood at epoch 6 : nan
likelihood at epoch 7 : nan
likelihood at epoch 7 : nan
likelihood at epoch 8 : nan
likelihood at epoch 8 : nan
likelihood at epoch 9 : nan
likelihood at epoch 9 : nan
likelihood at epoch 10 : nan
likelihood at epoch 10 : nan
```
I don't know how to deal with it, please help me~

And also, after a period, it raise file error about 
```[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_2/5_FOLD_MS/config_1/config_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_2/5_FOLD_MS/config_2/config_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_2/5_FOLD_MS/config_3/config_results.json'
...
```

**Comment by diningphil** [comment]
Try to change "node_type" in the config_CGMM.yml file to "discrete". The attributes for chemical datasets are discrete, and so it should be changed accordingly in the configuration file to use a categorical emission distribution. Let me know if this works, and I will add this in the README file. Thanks for pointing this out.

**Comment by duanyanan** [comment]
Thanks for your help! It does work! I change "node_type" to "discrete" as you say, "nan" error doesn't show again. But the console prints that 
```
Initializing layer 1 of CGMM...
Initializing layer 1 of CGMM...
Initializing layer 1 of CGMM...
Initializing layer 1 of CGMM...
Initializing layer 1 of CGMM...
Initializing layer 1 of CGMM...
Initializing layer 1 of CGMM...
Initializing layer 1 of CGMM...
...
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_2/5_FOLD_MS/config_1/config_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_2/5_FOLD_MS/config_2/config_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_2/5_FOLD_MS/config_3/config_results.json'
...
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_1/outer_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_2/outer_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_3/outer_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_4/outer_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_5/outer_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_6/outer_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_7/outer_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_8/outer_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_9/outer_results.json'
[Errno 2] No such file or directory: 'RESULTS/CGMM_NCI1_assessment/10_NESTED_CV/OUTER_FOLD_10/outer_results.json'
/home/anyua/dyn/CGMM/evaluation/risk_assessment/K_Fold_Assessment.py:53: RuntimeWarning: Mean of empty slice.
  assessment_results['avg_TR_score'] = outer_TR_scores.mean()
/home/anyua/anaconda3/envs/py3_pytorch/lib/python3.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/anyua/anaconda3/envs/py3_pytorch/lib/python3.7/site-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/anyua/anaconda3/envs/py3_pytorch/lib/python3.7/site-packages/numpy/core/_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/anyua/anaconda3/envs/py3_pytorch/lib/python3.7/site-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/anyua/dyn/CGMM/evaluation/risk_assessment/K_Fold_Assessment.py:55: RuntimeWarning: Mean of empty slice.
  assessment_results['avg_TS_score'] = outer_TS_scores.mean()
```
How can I resolve this file error?

**Comment by diningphil** [comment]
Try to remove the results folder associated to your old experiment. If It does not work, please use the  - - debug argument to investigate the error and paste it here.

**Comment by duanyanan** [comment]
I try to remove RESULTS then it still fails. As for debug mode, the console print as follow: 
```
(py3_pytorch) anyua@CV-Workstation:~/dyn/CGMM$ python Launch_Experiments.py --config-file config_CGMM.yml --inner-folds 5 --outer-folds 10 --dataset NCI1 --debug
Initializing layer 1 of CGMM...
Traceback (most recent call last):
  File "Launch_Experiments.py", line 48, in <module>
    raise e  # print(e)
  File "Launch_Experiments.py", line 46, in <module>
    debug=args.debug)
  File "/home/anyua/dyn/CGMM/Incremental_Evaluation.py", line 39, in main
    risk_assesser.risk_assessment(experiment_class, debug=debug)
  File "/home/anyua/dyn/CGMM/evaluation/risk_assessment/K_Fold_Assessment.py", line 85, in risk_assessment
    self._risk_assessment_helper(outer_k, experiment_class, kfold_folder, debug, other)
  File "/home/anyua/dyn/CGMM/evaluation/risk_assessment/K_Fold_Assessment.py", line 109, in _risk_assessment_helper
    self.model_configs, debug, other)
  File "/home/anyua/dyn/CGMM/evaluation/model_selection/K_Fold_Selection.py", line 88, in model_selection
    exp_config_name, other)
  File "/home/anyua/dyn/CGMM/evaluation/model_selection/K_Fold_Selection.py", line 133, in _model_selection_helper
    training_score, validation_score = experiment.run_valid(dataset_getter, logger, other)
  File "/home/anyua/dyn/CGMM/experiments/IncrementalExperiment.py", line 37, in run_valid
    resume=False, logger=logger, device=self.model_config['device'])
  File "/home/anyua/dyn/CGMM/models/incremental_architectures/IncrementalModel.py", line 178, in incremental_training
    validation_loader, device=device)
  File "/home/anyua/dyn/CGMM/models/graph_classifiers/CGMM.py", line 103, in train_layer
    l, eulaij = self.layer.E_step(x, statistics)
  File "/home/anyua/dyn/CGMM/models/graph_classifiers/CGMM.py", line 643, in E_step
    likelihood, posterior_estimate = self._E_step(labels, stats)
  File "/home/anyua/dyn/CGMM/models/graph_classifiers/CGMM.py", line 583, in _E_step
    emission_of_labels = self.emission.get_distribution_of_labels(labels)
  File "/home/anyua/dyn/CGMM/models/utils/CategoricalEmission.py", line 64, in get_distribution_of_labels
    emission_for_labels = torch.index_select(self.emission_distr, dim=0, index=labels_squeezed)  # ?xC
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #3 'index'
```

**Comment by diningphil** [comment]
I have fixed some minor issues that concerned the Categorical emission code (porting from another library did not successfully succeed). Now it should be fine.

However, notice that, to work on NCI1, you should change the following in the configuration file:
- model: from CGMMPPI to CGMM
- loss: from PPILoss to MulticlassClassificationLoss

I have pushed the config file. Let me know if it works now. Thanks for bringing up the issue.

**Comment by duanyanan** [comment]
I'm afraid that it still can't work... after I pull the new commits and I run cmd `python Launch_Experiments.py --config-file config_CGMM.yml --inner-folds 5 --outer-folds 10 --dataset NCI1 --debug`  console shows: 
```Initializing layer 1 of CGMM...
likelihood at epoch 1 : -458509.16928723
likelihood at epoch 2 : -200583.31092157125
likelihood at epoch 3 : -200583.31092198775
Initializing layer 2 of CGMM...
likelihood at epoch 1 : -520997.1636010354
likelihood at epoch 2 : -253431.28695711982
likelihood at epoch 3 : -253125.54211471078
likelihood at epoch 4 : -252605.35921404313
likelihood at epoch 5 : -251853.03314412548
likelihood at epoch 6 : -250844.49123776463
likelihood at epoch 7 : -249552.5415374191
likelihood at epoch 8 : -247952.3260814669
likelihood at epoch 9 : -246023.7453838443
likelihood at epoch 10 : -243758.772516734
Epoch: 1, TR loss: 0.6909660042191927 TR acc: 52.58413461538461, VL loss: 0.035354337982229284 VL acc: 2.810810810810811 TE loss: None TE acc: None
Epoch: 10, TR loss: 0.6689990389948854 TR acc: 58.74399038461539, VL loss: 0.03465532531609406 VL acc: 3.0405405405405403 TE loss: None TE acc: None
Epoch: 20, TR loss: 0.6589696284096974 TR acc: 60.60697115384615, VL loss: 0.03375356132919724 VL acc: 3.135135135135135 TE loss: None TE acc: None
Epoch: 30, TR loss: 0.6572369586747999 TR acc: 61.56850961538461, VL loss: 0.033795889809324936 VL acc: 3.1486486486486487 TE loss: None TE acc: None
...
Epoch: 660, TR loss: 0.6211583929924438 TR acc: 65.77524038461539, VL loss: 0.03349040738634161 VL acc: 3.2567567567567566 TE loss: None TE acc: None
Stopping at epoch 666, best is (0.6263092272700026, 64.9639423076923, 0.03287428432219737, 3.391891891891892, None, None, 166)
Traceback (most recent call last):
  File "Launch_Experiments.py", line 48, in <module>
    raise e  # print(e)
  File "Launch_Experiments.py", line 46, in <module>
    debug=args.debug)
  File "/home/anyua/dyn/CGMM/Incremental_Evaluation.py", line 39, in main
    risk_assesser.risk_assessment(experiment_class, debug=debug)
  File "/home/anyua/dyn/CGMM/evaluation/risk_assessment/K_Fold_Assessment.py", line 85, in risk_assessment
    self._risk_assessment_helper(outer_k, experiment_class, kfold_folder, debug, other)
  File "/home/anyua/dyn/CGMM/evaluation/risk_assessment/K_Fold_Assessment.py", line 109, in _risk_assessment_helper
    self.model_configs, debug, other)
  File "/home/anyua/dyn/CGMM/evaluation/model_selection/K_Fold_Selection.py", line 88, in model_selection
    exp_config_name, other)
  File "/home/anyua/dyn/CGMM/evaluation/model_selection/K_Fold_Selection.py", line 133, in _model_selection_helper
    training_score, validation_score = experiment.run_valid(dataset_getter, logger, other)
  File "/home/anyua/dyn/CGMM/experiments/IncrementalExperiment.py", line 30, in run_valid
    shuffle=shuffle)
  File "/home/anyua/dyn/CGMM/evaluation/dataset_getter.py", line 13, in get_train_val
    return dataset.get_model_selection_fold(self.outer_k, self.inner_k, batch_size, shuffle)
  File "/home/anyua/dyn/CGMM/Datasets/manager.py", line 204, in get_model_selection_fold
    idxs = self.splits[outer_idx]["model_selection"][inner_idx]
IndexError: list index out of range
```
I'm confused why a file error becomes a IndexError, it's so depressing:(

**Comment by diningphil** [comment]
Sorry for the inconvenience, these are very busy days. Let me go back to you in a few days, I will try to solve the issue for good. Thank you for your patience.

**Comment by duanyanan** [comment]
OK. Really thank you for your help~ I wish you can work it out and I'm looking forward it.

**Comment by diningphil** [comment]
I have just noticed that you are using the wrong --inner-fold argument. You are using 5, but the default split creation of the data uses 10-fold CV for model assessment and hold-out (90/10 split) for model selection. Try changing the argument to --inner-fold=None instead of 5. It is working for me.

**Comment by duanyanan** [comment]
It works for me, too. Appreciate your help and thank you for your study.
